// generated by @ng-toolkit/universal
const port = process.env.PORT || 443;
const server = require('./dist/server');
var fs = require('fs'), 
 https = require('https');
var options  = { 
 key: fs.readFileSync('./ssl/ssl.key'),
 cert: fs.readFileSync('./ssl/ssl.crt')
};
var httpsServer = https.createServer(options, server.app)
 .listen(port, () => {
  console.log("Express server listening on port " + port);
 });